import pytest

from fractal_ome_zarr_hcs_stitching.stitching_task import stitching_task


@pytest.mark.parametrize(
    "registration_resolution_level",
    [res_level for res_level in [0, 1]],
)
def test_stitching_2d_grid(
    tiled_ome_zarr_2d,
    registration_resolution_level,
):
    image_list_updates = stitching_task(
        zarr_url=tiled_ome_zarr_2d,
        registration_channel_label="DAPI",
        registration_resolution_level=registration_resolution_level,
    )
    expected_image_list_updates = {
        "image_list_updates": [
            {
                "zarr_url": f"{tiled_ome_zarr_2d}_fused",
                "origin": tiled_ome_zarr_2d,
            }
        ]
    }
    print(tiled_ome_zarr_2d)
    assert image_list_updates == expected_image_list_updates

    # Currently does not create reasonable stitching
    # One can check out the outputs generated by the test & use this to tune
    # settings
